/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { RegionService } from "../region.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { RegionCreateInput } from "./RegionCreateInput";
import { RegionWhereInput } from "./RegionWhereInput";
import { RegionWhereUniqueInput } from "./RegionWhereUniqueInput";
import { RegionFindManyArgs } from "./RegionFindManyArgs";
import { RegionUpdateInput } from "./RegionUpdateInput";
import { Region } from "./Region";
import { CountyFindManyArgs } from "../../county/base/CountyFindManyArgs";
import { County } from "../../county/base/County";
import { CountyWhereUniqueInput } from "../../county/base/CountyWhereUniqueInput";
import { ProjectHasRegionFindManyArgs } from "../../projectHasRegion/base/ProjectHasRegionFindManyArgs";
import { ProjectHasRegion } from "../../projectHasRegion/base/ProjectHasRegion";
import { ProjectHasRegionWhereUniqueInput } from "../../projectHasRegion/base/ProjectHasRegionWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class RegionControllerBase {
  constructor(
    protected readonly service: RegionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Region",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Region })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: RegionCreateInput): Promise<Region> {
    return await this.service.create({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Region",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Region] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(RegionFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Region[]> {
    const args = plainToClass(RegionFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Region",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Region })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: RegionWhereUniqueInput
  ): Promise<Region | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Region",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Region })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: RegionWhereUniqueInput,
    @common.Body() data: RegionUpdateInput
  ): Promise<Region | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Region",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Region })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: RegionWhereUniqueInput
  ): Promise<Region | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "County",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/counties")
  @ApiNestedQuery(CountyFindManyArgs)
  async findManyCounties(
    @common.Req() request: Request,
    @common.Param() params: RegionWhereUniqueInput
  ): Promise<County[]> {
    const query = plainToClass(CountyFindManyArgs, request.query);
    const results = await this.service.findCounties(params.id, {
      ...query,
      select: {
        code: true,
        createdAt: true,
        id: true,
        name: true,

        region: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Region",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/counties")
  async connectCounties(
    @common.Param() params: RegionWhereUniqueInput,
    @common.Body() body: CountyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      counties: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Region",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/counties")
  async updateCounties(
    @common.Param() params: RegionWhereUniqueInput,
    @common.Body() body: CountyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      counties: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Region",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/counties")
  async disconnectCounties(
    @common.Param() params: RegionWhereUniqueInput,
    @common.Body() body: CountyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      counties: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ProjectHasRegion",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/projectHasRegions")
  @ApiNestedQuery(ProjectHasRegionFindManyArgs)
  async findManyProjectHasRegions(
    @common.Req() request: Request,
    @common.Param() params: RegionWhereUniqueInput
  ): Promise<ProjectHasRegion[]> {
    const query = plainToClass(ProjectHasRegionFindManyArgs, request.query);
    const results = await this.service.findProjectHasRegions(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        project: {
          select: {
            id: true,
          },
        },

        region: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Region",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/projectHasRegions")
  async connectProjectHasRegions(
    @common.Param() params: RegionWhereUniqueInput,
    @common.Body() body: ProjectHasRegionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      projectHasRegions: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Region",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/projectHasRegions")
  async updateProjectHasRegions(
    @common.Param() params: RegionWhereUniqueInput,
    @common.Body() body: ProjectHasRegionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      projectHasRegions: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Region",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/projectHasRegions")
  async disconnectProjectHasRegions(
    @common.Param() params: RegionWhereUniqueInput,
    @common.Body() body: ProjectHasRegionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      projectHasRegions: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
