/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ConstituencyUpdateManyWithoutProjectsInput } from "./ConstituencyUpdateManyWithoutProjectsInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { CountyUpdateManyWithoutProjectsInput } from "./CountyUpdateManyWithoutProjectsInput";
import { MediumUpdateManyWithoutProjectsInput } from "./MediumUpdateManyWithoutProjectsInput";
import { RegionUpdateManyWithoutProjectsInput } from "./RegionUpdateManyWithoutProjectsInput";
@InputType()
class ProjectUpdateInput {
  @ApiProperty({
    required: false,
    type: () => ConstituencyUpdateManyWithoutProjectsInput,
  })
  @ValidateNested()
  @Type(() => ConstituencyUpdateManyWithoutProjectsInput)
  @IsOptional()
  @Field(() => ConstituencyUpdateManyWithoutProjectsInput, {
    nullable: true,
  })
  constituencies?: ConstituencyUpdateManyWithoutProjectsInput;

  @ApiProperty({
    required: false,
    type: () => CountyUpdateManyWithoutProjectsInput,
  })
  @ValidateNested()
  @Type(() => CountyUpdateManyWithoutProjectsInput)
  @IsOptional()
  @Field(() => CountyUpdateManyWithoutProjectsInput, {
    nullable: true,
  })
  counties?: CountyUpdateManyWithoutProjectsInput;

  @ApiProperty({
    required: false,
    type: () => MediumUpdateManyWithoutProjectsInput,
  })
  @ValidateNested()
  @Type(() => MediumUpdateManyWithoutProjectsInput)
  @IsOptional()
  @Field(() => MediumUpdateManyWithoutProjectsInput, {
    nullable: true,
  })
  mediums?: MediumUpdateManyWithoutProjectsInput;

  @ApiProperty({
    required: false,
    type: () => RegionUpdateManyWithoutProjectsInput,
  })
  @ValidateNested()
  @Type(() => RegionUpdateManyWithoutProjectsInput)
  @IsOptional()
  @Field(() => RegionUpdateManyWithoutProjectsInput, {
    nullable: true,
  })
  regions?: RegionUpdateManyWithoutProjectsInput;
}
export { ProjectUpdateInput };
