/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ConstituencyCreateNestedManyWithoutProjectsInput } from "./ConstituencyCreateNestedManyWithoutProjectsInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { CountyCreateNestedManyWithoutProjectsInput } from "./CountyCreateNestedManyWithoutProjectsInput";
import { MediumCreateNestedManyWithoutProjectsInput } from "./MediumCreateNestedManyWithoutProjectsInput";
import { RegionCreateNestedManyWithoutProjectsInput } from "./RegionCreateNestedManyWithoutProjectsInput";
@InputType()
class ProjectCreateInput {
  @ApiProperty({
    required: true,
    type: () => ConstituencyCreateNestedManyWithoutProjectsInput,
  })
  @ValidateNested()
  @Type(() => ConstituencyCreateNestedManyWithoutProjectsInput)
  @IsOptional()
  @Field(() => ConstituencyCreateNestedManyWithoutProjectsInput, {
    nullable: true,
  })
  constituencies?: ConstituencyCreateNestedManyWithoutProjectsInput;

  @ApiProperty({
    required: true,
    type: () => CountyCreateNestedManyWithoutProjectsInput,
  })
  @ValidateNested()
  @Type(() => CountyCreateNestedManyWithoutProjectsInput)
  @IsOptional()
  @Field(() => CountyCreateNestedManyWithoutProjectsInput, {
    nullable: true,
  })
  counties?: CountyCreateNestedManyWithoutProjectsInput;

  @ApiProperty({
    required: false,
    type: () => MediumCreateNestedManyWithoutProjectsInput,
  })
  @ValidateNested()
  @Type(() => MediumCreateNestedManyWithoutProjectsInput)
  @IsOptional()
  @Field(() => MediumCreateNestedManyWithoutProjectsInput, {
    nullable: true,
  })
  mediums?: MediumCreateNestedManyWithoutProjectsInput;

  @ApiProperty({
    required: true,
    type: () => RegionCreateNestedManyWithoutProjectsInput,
  })
  @ValidateNested()
  @Type(() => RegionCreateNestedManyWithoutProjectsInput)
  @IsOptional()
  @Field(() => RegionCreateNestedManyWithoutProjectsInput, {
    nullable: true,
  })
  regions?: RegionCreateNestedManyWithoutProjectsInput;
}
export { ProjectCreateInput };
