/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ConstituencyListRelationFilter } from "../../constituency/base/ConstituencyListRelationFilter";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { CountyListRelationFilter } from "../../county/base/CountyListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { MediumListRelationFilter } from "../../medium/base/MediumListRelationFilter";
import { RegionListRelationFilter } from "../../region/base/RegionListRelationFilter";
@InputType()
class ProjectWhereInput {
  @ApiProperty({
    required: false,
    type: () => ConstituencyListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ConstituencyListRelationFilter)
  @IsOptional()
  @Field(() => ConstituencyListRelationFilter, {
    nullable: true,
  })
  constituencies?: ConstituencyListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => CountyListRelationFilter,
  })
  @ValidateNested()
  @Type(() => CountyListRelationFilter)
  @IsOptional()
  @Field(() => CountyListRelationFilter, {
    nullable: true,
  })
  counties?: CountyListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => MediumListRelationFilter,
  })
  @ValidateNested()
  @Type(() => MediumListRelationFilter)
  @IsOptional()
  @Field(() => MediumListRelationFilter, {
    nullable: true,
  })
  mediums?: MediumListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => RegionListRelationFilter,
  })
  @ValidateNested()
  @Type(() => RegionListRelationFilter)
  @IsOptional()
  @Field(() => RegionListRelationFilter, {
    nullable: true,
  })
  regions?: RegionListRelationFilter;
}
export { ProjectWhereInput };
