/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { MediumListRelationFilter } from "../../medium/base/MediumListRelationFilter";
import { ProjectHasConstituencyListRelationFilter } from "../../projectHasConstituency/base/ProjectHasConstituencyListRelationFilter";
import { ProjectHasCountyListRelationFilter } from "../../projectHasCounty/base/ProjectHasCountyListRelationFilter";
import { ProjectHasRegionListRelationFilter } from "../../projectHasRegion/base/ProjectHasRegionListRelationFilter";
@InputType()
class ProjectWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => MediumListRelationFilter,
  })
  @ValidateNested()
  @Type(() => MediumListRelationFilter)
  @IsOptional()
  @Field(() => MediumListRelationFilter, {
    nullable: true,
  })
  mediums?: MediumListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => ProjectHasConstituencyListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ProjectHasConstituencyListRelationFilter)
  @IsOptional()
  @Field(() => ProjectHasConstituencyListRelationFilter, {
    nullable: true,
  })
  projectHasConstituencies?: ProjectHasConstituencyListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => ProjectHasCountyListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ProjectHasCountyListRelationFilter)
  @IsOptional()
  @Field(() => ProjectHasCountyListRelationFilter, {
    nullable: true,
  })
  projectHasCounties?: ProjectHasCountyListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => ProjectHasRegionListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ProjectHasRegionListRelationFilter)
  @IsOptional()
  @Field(() => ProjectHasRegionListRelationFilter, {
    nullable: true,
  })
  projectHasRegions?: ProjectHasRegionListRelationFilter;
}
export { ProjectWhereInput };
