/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateCountyArgs } from "./CreateCountyArgs";
import { UpdateCountyArgs } from "./UpdateCountyArgs";
import { DeleteCountyArgs } from "./DeleteCountyArgs";
import { CountyFindManyArgs } from "./CountyFindManyArgs";
import { CountyFindUniqueArgs } from "./CountyFindUniqueArgs";
import { County } from "./County";
import { Project } from "../../project/base/Project";
import { Region } from "../../region/base/Region";
import { CountyService } from "../county.service";

@graphql.Resolver(() => County)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class CountyResolverBase {
  constructor(
    protected readonly service: CountyService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "County",
    action: "read",
    possession: "any",
  })
  async _countiesMeta(
    @graphql.Args() args: CountyFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [County])
  @nestAccessControl.UseRoles({
    resource: "County",
    action: "read",
    possession: "any",
  })
  async counties(@graphql.Args() args: CountyFindManyArgs): Promise<County[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => County, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "County",
    action: "read",
    possession: "own",
  })
  async county(
    @graphql.Args() args: CountyFindUniqueArgs
  ): Promise<County | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => County)
  @nestAccessControl.UseRoles({
    resource: "County",
    action: "create",
    possession: "any",
  })
  async createCounty(@graphql.Args() args: CreateCountyArgs): Promise<County> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        project: args.data.project
          ? {
              connect: args.data.project,
            }
          : undefined,

        region: args.data.region
          ? {
              connect: args.data.region,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => County)
  @nestAccessControl.UseRoles({
    resource: "County",
    action: "update",
    possession: "any",
  })
  async updateCounty(
    @graphql.Args() args: UpdateCountyArgs
  ): Promise<County | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          project: args.data.project
            ? {
                connect: args.data.project,
              }
            : undefined,

          region: args.data.region
            ? {
                connect: args.data.region,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => County)
  @nestAccessControl.UseRoles({
    resource: "County",
    action: "delete",
    possession: "any",
  })
  async deleteCounty(
    @graphql.Args() args: DeleteCountyArgs
  ): Promise<County | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Project, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Project",
    action: "read",
    possession: "any",
  })
  async project(@graphql.Parent() parent: County): Promise<Project | null> {
    const result = await this.service.getProject(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Region, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Region",
    action: "read",
    possession: "any",
  })
  async region(@graphql.Parent() parent: County): Promise<Region | null> {
    const result = await this.service.getRegion(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
