/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CountyService } from "../county.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CountyCreateInput } from "./CountyCreateInput";
import { CountyWhereInput } from "./CountyWhereInput";
import { CountyWhereUniqueInput } from "./CountyWhereUniqueInput";
import { CountyFindManyArgs } from "./CountyFindManyArgs";
import { CountyUpdateInput } from "./CountyUpdateInput";
import { County } from "./County";
import { ProjectHasCountyFindManyArgs } from "../../projectHasCounty/base/ProjectHasCountyFindManyArgs";
import { ProjectHasCounty } from "../../projectHasCounty/base/ProjectHasCounty";
import { ProjectHasCountyWhereUniqueInput } from "../../projectHasCounty/base/ProjectHasCountyWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CountyControllerBase {
  constructor(
    protected readonly service: CountyService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "County",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: County })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: CountyCreateInput): Promise<County> {
    return await this.service.create({
      data: {
        ...data,

        region: data.region
          ? {
              connect: data.region,
            }
          : undefined,
      },
      select: {
        code: true,
        createdAt: true,
        id: true,
        name: true,

        region: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "County",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [County] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(CountyFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<County[]> {
    const args = plainToClass(CountyFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        code: true,
        createdAt: true,
        id: true,
        name: true,

        region: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "County",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: County })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: CountyWhereUniqueInput
  ): Promise<County | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        code: true,
        createdAt: true,
        id: true,
        name: true,

        region: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "County",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: County })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: CountyWhereUniqueInput,
    @common.Body() data: CountyUpdateInput
  ): Promise<County | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          region: data.region
            ? {
                connect: data.region,
              }
            : undefined,
        },
        select: {
          code: true,
          createdAt: true,
          id: true,
          name: true,

          region: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "County",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: County })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: CountyWhereUniqueInput
  ): Promise<County | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          code: true,
          createdAt: true,
          id: true,
          name: true,

          region: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ProjectHasCounty",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/projectHasCounties")
  @ApiNestedQuery(ProjectHasCountyFindManyArgs)
  async findManyProjectHasCounties(
    @common.Req() request: Request,
    @common.Param() params: CountyWhereUniqueInput
  ): Promise<ProjectHasCounty[]> {
    const query = plainToClass(ProjectHasCountyFindManyArgs, request.query);
    const results = await this.service.findProjectHasCounties(params.id, {
      ...query,
      select: {
        county: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,

        project: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "County",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/projectHasCounties")
  async connectProjectHasCounties(
    @common.Param() params: CountyWhereUniqueInput,
    @common.Body() body: ProjectHasCountyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      projectHasCounties: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "County",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/projectHasCounties")
  async updateProjectHasCounties(
    @common.Param() params: CountyWhereUniqueInput,
    @common.Body() body: ProjectHasCountyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      projectHasCounties: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "County",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/projectHasCounties")
  async disconnectProjectHasCounties(
    @common.Param() params: CountyWhereUniqueInput,
    @common.Body() body: ProjectHasCountyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      projectHasCounties: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
