/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ProjectHasConstituencyService } from "../projectHasConstituency.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ProjectHasConstituencyCreateInput } from "./ProjectHasConstituencyCreateInput";
import { ProjectHasConstituencyWhereInput } from "./ProjectHasConstituencyWhereInput";
import { ProjectHasConstituencyWhereUniqueInput } from "./ProjectHasConstituencyWhereUniqueInput";
import { ProjectHasConstituencyFindManyArgs } from "./ProjectHasConstituencyFindManyArgs";
import { ProjectHasConstituencyUpdateInput } from "./ProjectHasConstituencyUpdateInput";
import { ProjectHasConstituency } from "./ProjectHasConstituency";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ProjectHasConstituencyControllerBase {
  constructor(
    protected readonly service: ProjectHasConstituencyService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ProjectHasConstituency",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ProjectHasConstituency })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: ProjectHasConstituencyCreateInput
  ): Promise<ProjectHasConstituency> {
    return await this.service.create({
      data: {
        ...data,

        constituency: {
          connect: data.constituency,
        },

        project: {
          connect: data.project,
        },
      },
      select: {
        constituency: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,

        project: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ProjectHasConstituency",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [ProjectHasConstituency] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(ProjectHasConstituencyFindManyArgs)
  async findMany(
    @common.Req() request: Request
  ): Promise<ProjectHasConstituency[]> {
    const args = plainToClass(
      ProjectHasConstituencyFindManyArgs,
      request.query
    );
    return this.service.findMany({
      ...args,
      select: {
        constituency: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,

        project: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ProjectHasConstituency",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ProjectHasConstituency })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: ProjectHasConstituencyWhereUniqueInput
  ): Promise<ProjectHasConstituency | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        constituency: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,

        project: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ProjectHasConstituency",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ProjectHasConstituency })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: ProjectHasConstituencyWhereUniqueInput,
    @common.Body() data: ProjectHasConstituencyUpdateInput
  ): Promise<ProjectHasConstituency | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          constituency: {
            connect: data.constituency,
          },

          project: {
            connect: data.project,
          },
        },
        select: {
          constituency: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,

          project: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "ProjectHasConstituency",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ProjectHasConstituency })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: ProjectHasConstituencyWhereUniqueInput
  ): Promise<ProjectHasConstituency | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          constituency: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,

          project: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
